### ISSUE TITLE
Color contrast in light mode is bad

### ISSUE THREAD

**Issue by kidonng** [solelychloe/arciniega.one#10]
Hi! I stumbled upon your great website, and noticed the color contrast in light mode is bad:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/44045911/226100471-2fafeb62-1575-4905-b973-9495b28c3abb.png">

Chrome DevTools' CSS overview suggests the same:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/44045911/226100484-57dbbcb0-f28f-4abe-861e-a26e9ea3b4d8.png">

Dark mode looks fine, but not everyone prefer it (especially since that's not the default most of the time).

<img width="578" alt="image" src="https://user-images.githubusercontent.com/44045911/226100520-3e0bedde-25af-4e8f-b2e2-e3eb919206dd.png">

**Comment by solelychloe** [comment]
Hi there! 
Thank you for bringing this to my attention.

I have resolved this issue with the commit 0271ad8. The contrast should (hopefully) be easy on the eyes now.
